# Generated by Django 3.0.3 on 2020-02-21 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciation', models.CharField(max_length=1000, verbose_name='Enunciado')),
                ('company', models.CharField(max_length=100, verbose_name='Banca')),
                ('subject', models.CharField(max_length=100, verbose_name='Assunto')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Opção')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Está correto')),
                ('enunciation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Question')),
            ],
        ),
        migrations.AddConstraint(
            model_name='option',
            constraint=models.UniqueConstraint(fields=('enunciation', 'text'), name='unique_text_enunciation'),
        ),
    ]
